"""Nifty 500 extension: 280 mid/small-cap NSE stocks (mostly market cap > 1000 Cr)
to extend Nifty 200 → Nifty 500 universe.
"""

NIFTY_500_EXTRA = [
    # Banking / Financial
    {"symbol": "KARURVYSYA", "name": "Karur Vysya Bank", "sector": "Financial"},
    {"symbol": "CUB", "name": "City Union Bank", "sector": "Financial"},
    {"symbol": "SOUTHBANK", "name": "South Indian Bank", "sector": "Financial"},
    {"symbol": "KTKBANK", "name": "Karnataka Bank", "sector": "Financial"},
    {"symbol": "IDBI", "name": "IDBI Bank", "sector": "Financial"},
    {"symbol": "DCBBANK", "name": "DCB Bank", "sector": "Financial"},
    {"symbol": "EQUITASBNK", "name": "Equitas SFB", "sector": "Financial"},
    {"symbol": "ESAFSFB", "name": "ESAF SFB", "sector": "Financial"},
    {"symbol": "UJJIVAN", "name": "Ujjivan Financial", "sector": "Financial"},
    {"symbol": "MOTILALOFS", "name": "Motilal Oswal Financial", "sector": "Financial"},
    {"symbol": "EDELWEISS", "name": "Edelweiss Financial", "sector": "Financial"},
    {"symbol": "JMFINANCIL", "name": "JM Financial", "sector": "Financial"},
    {"symbol": "ICICIGI", "name": "ICICI Lombard", "sector": "Insurance"},
    {"symbol": "ANGELONE", "name": "Angel One", "sector": "Financial"},
    {"symbol": "HDFCSEC", "name": "HDFC Securities", "sector": "Financial"},
    {"symbol": "ICICISEC", "name": "ICICI Securities", "sector": "Financial"},
    {"symbol": "GICRE", "name": "GIC Re", "sector": "Insurance"},
    {"symbol": "NIACL", "name": "New India Assurance", "sector": "Insurance"},
    {"symbol": "MAXFIN", "name": "Max Financial", "sector": "Insurance"},
    {"symbol": "CAPRIGLOB", "name": "Capri Global Capital", "sector": "Financial"},
    {"symbol": "SBFC", "name": "SBFC Finance", "sector": "Financial"},
    {"symbol": "FIVESTAR", "name": "Five-Star Business", "sector": "Financial"},
    {"symbol": "CREDITACC", "name": "CreditAccess Grameen", "sector": "Financial"},
    {"symbol": "AAVAS", "name": "Aavas Financiers", "sector": "Financial"},
    {"symbol": "HOMEFIRST", "name": "Home First Finance", "sector": "Financial"},
    {"symbol": "REPCOHOME", "name": "Repco Home Finance", "sector": "Financial"},
    # Auto
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland", "sector": "Auto"},
    {"symbol": "BAJAJHLDNG", "name": "Bajaj Holdings", "sector": "Auto"},
    {"symbol": "SUNDRMFAST", "name": "Sundram Fasteners", "sector": "Auto"},
    {"symbol": "MOTHERSON", "name": "Motherson Sumi", "sector": "Auto"},
    {"symbol": "AMARAJABAT", "name": "Amara Raja", "sector": "Auto"},
    {"symbol": "MRF", "name": "MRF", "sector": "Auto"},
    {"symbol": "APOLLOTYRE", "name": "Apollo Tyres", "sector": "Auto"},
    {"symbol": "CEATLTD", "name": "CEAT", "sector": "Auto"},
    {"symbol": "JKTYRE", "name": "JK Tyre", "sector": "Auto"},
    {"symbol": "SCHAEFFLER", "name": "Schaeffler India", "sector": "Auto"},
    {"symbol": "ENDURANCE", "name": "Endurance Tech", "sector": "Auto"},
    {"symbol": "MINDAIND", "name": "Uno Minda", "sector": "Auto"},
    {"symbol": "GREAVESCOT", "name": "Greaves Cotton", "sector": "Auto"},
    {"symbol": "RAMKY", "name": "Ramky Infrastructure", "sector": "Auto"},
    {"symbol": "JAMNAAUTO", "name": "Jamna Auto Industries", "sector": "Auto"},
    {"symbol": "RKFORGE", "name": "Ramkrishna Forgings", "sector": "Auto"},
    # Pharma
    {"symbol": "GRANULES", "name": "Granules India", "sector": "Pharma"},
    {"symbol": "AJANTPHARM", "name": "Ajanta Pharma", "sector": "Pharma"},
    {"symbol": "NATCOPHARM", "name": "Natco Pharma", "sector": "Pharma"},
    {"symbol": "JBCHEPHARM", "name": "JB Chemicals", "sector": "Pharma"},
    {"symbol": "WOCKPHARMA", "name": "Wockhardt", "sector": "Pharma"},
    {"symbol": "FDC", "name": "FDC Limited", "sector": "Pharma"},
    {"symbol": "STAR", "name": "Strides Pharma", "sector": "Pharma"},
    {"symbol": "INDOCO", "name": "Indoco Remedies", "sector": "Pharma"},
    {"symbol": "MARKSANS", "name": "Marksans Pharma", "sector": "Pharma"},
    {"symbol": "SANOFI", "name": "Sanofi India", "sector": "Pharma"},
    {"symbol": "PFIZER", "name": "Pfizer Limited", "sector": "Pharma"},
    {"symbol": "GLAXO", "name": "GSK Pharma", "sector": "Pharma"},
    {"symbol": "ERIS", "name": "Eris Lifesciences", "sector": "Pharma"},
    {"symbol": "CAPLIPOINT", "name": "Caplin Point Labs", "sector": "Pharma"},
    {"symbol": "SUVENPHAR", "name": "Suven Pharmaceuticals", "sector": "Pharma"},
    {"symbol": "POLYMED", "name": "Poly Medicure", "sector": "Healthcare"},
    {"symbol": "MEDPLUS", "name": "Medplus Health", "sector": "Healthcare"},
    {"symbol": "FORTIS", "name": "Fortis Healthcare", "sector": "Healthcare"},
    {"symbol": "MAXHEALTH", "name": "Max Healthcare", "sector": "Healthcare"},
    {"symbol": "NH", "name": "Narayana Hrudayalaya", "sector": "Healthcare"},
    {"symbol": "RAINBOW", "name": "Rainbow Children's Medicare", "sector": "Healthcare"},
    {"symbol": "KIMS", "name": "Krishna Institute Med Sci", "sector": "Healthcare"},
    {"symbol": "VIJAYA", "name": "Vijaya Diagnostic", "sector": "Healthcare"},
    {"symbol": "METROPOLIS", "name": "Metropolis Healthcare", "sector": "Healthcare"},
    {"symbol": "DRLALPATHLAB", "name": "Dr Lal PathLabs", "sector": "Healthcare"},
    {"symbol": "THYROCARE", "name": "Thyrocare Tech", "sector": "Healthcare"},
    # IT
    {"symbol": "BIRLASOFT", "name": "Birlasoft", "sector": "IT"},
    {"symbol": "RAMCOSYS", "name": "Ramco Systems", "sector": "IT"},
    {"symbol": "INTELLECT", "name": "Intellect Design Arena", "sector": "IT"},
    {"symbol": "NIITLTD", "name": "NIIT Limited", "sector": "IT"},
    {"symbol": "FIRSTCRY", "name": "FirstCry (Brainbees)", "sector": "Internet"},
    {"symbol": "EMUDHRA", "name": "eMudhra", "sector": "IT"},
    {"symbol": "ROUTE", "name": "Route Mobile", "sector": "IT"},
    {"symbol": "TANLA", "name": "Tanla Platforms", "sector": "IT"},
    {"symbol": "ZENTEC", "name": "Zen Technologies", "sector": "IT"},
    {"symbol": "MASTEK", "name": "Mastek", "sector": "IT"},
    {"symbol": "SONATSOFTW", "name": "Sonata Software", "sector": "IT"},
    {"symbol": "NEWGEN", "name": "Newgen Software", "sector": "IT"},
    {"symbol": "HAPPSTMNDS", "name": "Happiest Minds", "sector": "IT"},
    {"symbol": "SAGCEM", "name": "Sagar Cements", "sector": "Cement"},
    {"symbol": "STAR-CEM", "name": "Star Cement", "sector": "Cement"},
    {"symbol": "JKLAKSHMI", "name": "JK Lakshmi Cement", "sector": "Cement"},
    {"symbol": "DALBHARAT", "name": "Dalmia Bharat", "sector": "Cement"},
    {"symbol": "INDIACEM", "name": "India Cements", "sector": "Cement"},
    {"symbol": "BIRLACORPN", "name": "Birla Corporation", "sector": "Cement"},
    {"symbol": "HEIDELBERG", "name": "HeidelbergCement India", "sector": "Cement"},
    {"symbol": "PRSMJOHNSN", "name": "Prism Johnson", "sector": "Cement"},
    # FMCG / Consumer
    {"symbol": "GILLETTE", "name": "Gillette India", "sector": "FMCG"},
    {"symbol": "PGHH", "name": "P&G Hygiene", "sector": "FMCG"},
    {"symbol": "EMAMILTD", "name": "Emami", "sector": "FMCG"},
    {"symbol": "JYOTHYLAB", "name": "Jyothy Labs", "sector": "FMCG"},
    {"symbol": "RADICO", "name": "Radico Khaitan", "sector": "FMCG"},
    {"symbol": "BAJAJCON", "name": "Bajaj Consumer Care", "sector": "FMCG"},
    {"symbol": "CCL", "name": "CCL Products", "sector": "FMCG"},
    {"symbol": "KRBL", "name": "KRBL", "sector": "FMCG"},
    {"symbol": "VENKEYS", "name": "Venky's India", "sector": "FMCG"},
    {"symbol": "AVANTIFEED", "name": "Avanti Feeds", "sector": "FMCG"},
    {"symbol": "VARUN", "name": "Varun Beverages", "sector": "FMCG"},
    {"symbol": "DEVYANI", "name": "Devyani International", "sector": "Consumer"},
    {"symbol": "WESTLIFE", "name": "Westlife Foodworld", "sector": "Consumer"},
    {"symbol": "SAPPHIRE", "name": "Sapphire Foods", "sector": "Consumer"},
    {"symbol": "BAJAJELEC", "name": "Bajaj Electricals", "sector": "Consumer"},
    {"symbol": "WHIRLPOOL", "name": "Whirlpool of India", "sector": "Consumer"},
    {"symbol": "VOLTAS", "name": "Voltas", "sector": "Consumer"},
    {"symbol": "BLUESTARCO", "name": "Blue Star", "sector": "Consumer"},
    {"symbol": "TTKPRESTIG", "name": "TTK Prestige", "sector": "Consumer"},
    {"symbol": "ORIENTELEC", "name": "Orient Electric", "sector": "Consumer"},
    {"symbol": "SYMPHONY", "name": "Symphony", "sector": "Consumer"},
    {"symbol": "AMBER", "name": "Amber Enterprises", "sector": "Consumer"},
    {"symbol": "GREAVECOT", "name": "Greaves Cotton", "sector": "Consumer"},
    {"symbol": "EICHERMOT", "name": "Eicher Motors", "sector": "Auto"},
    # Metals / Industrial
    {"symbol": "WELCORP", "name": "Welspun Corp", "sector": "Metals"},
    {"symbol": "JINDALSAW", "name": "Jindal Saw", "sector": "Metals"},
    {"symbol": "RATNAMANI", "name": "Ratnamani Metals", "sector": "Metals"},
    {"symbol": "MOIL", "name": "MOIL", "sector": "Metals"},
    {"symbol": "GMDCLTD", "name": "GMDC", "sector": "Metals"},
    {"symbol": "GRAVITA", "name": "Gravita India", "sector": "Metals"},
    {"symbol": "JTEKTINDIA", "name": "Jtekt India", "sector": "Capital Goods"},
    {"symbol": "ABB", "name": "ABB India", "sector": "Capital Goods"},
    {"symbol": "HONAUT", "name": "Honeywell Automation", "sector": "Capital Goods"},
    {"symbol": "GRINDWELL", "name": "Grindwell Norton", "sector": "Capital Goods"},
    {"symbol": "TIMKEN", "name": "Timken India", "sector": "Capital Goods"},
    {"symbol": "SKFINDIA", "name": "SKF India", "sector": "Capital Goods"},
    {"symbol": "INGERRAND", "name": "Ingersoll Rand India", "sector": "Capital Goods"},
    {"symbol": "ELGIEQUIP", "name": "Elgi Equipments", "sector": "Capital Goods"},
    {"symbol": "ESABINDIA", "name": "ESAB India", "sector": "Capital Goods"},
    {"symbol": "AIAENG", "name": "AIA Engineering", "sector": "Capital Goods"},
    {"symbol": "KSB", "name": "KSB", "sector": "Capital Goods"},
    {"symbol": "GMMPFAUDLR", "name": "GMM Pfaudler", "sector": "Capital Goods"},
    {"symbol": "ASTERDM", "name": "Aster DM Healthcare", "sector": "Healthcare"},
    {"symbol": "ZENSARTECH", "name": "Zensar Technologies", "sector": "IT"},
    {"symbol": "FINEORG", "name": "Fine Organic Industries", "sector": "Chemicals"},
    {"symbol": "NAVINFLUOR", "name": "Navin Fluorine", "sector": "Chemicals"},
    {"symbol": "GUJALKALI", "name": "Gujarat Alkalies", "sector": "Chemicals"},
    {"symbol": "GHCL", "name": "GHCL", "sector": "Chemicals"},
    {"symbol": "ALKYLAMINE", "name": "Alkyl Amines", "sector": "Chemicals"},
    {"symbol": "VINATIORGA", "name": "Vinati Organics", "sector": "Chemicals"},
    {"symbol": "BALAMINES", "name": "Balaji Amines", "sector": "Chemicals"},
    {"symbol": "TATACHEM", "name": "Tata Chemicals", "sector": "Chemicals"},
    {"symbol": "ROSSARI", "name": "Rossari Biotech", "sector": "Chemicals"},
    {"symbol": "CLEAN", "name": "Clean Science", "sector": "Chemicals"},
    {"symbol": "GALAXYSURF", "name": "Galaxy Surfactants", "sector": "Chemicals"},
    {"symbol": "ATUL", "name": "Atul", "sector": "Chemicals"},
    {"symbol": "SUDARSCHEM", "name": "Sudarshan Chemical", "sector": "Chemicals"},
    {"symbol": "PCBL", "name": "PCBL Limited", "sector": "Chemicals"},
    {"symbol": "AKZOINDIA", "name": "Akzo Nobel India", "sector": "Chemicals"},
    {"symbol": "KANSAINER", "name": "Kansai Nerolac", "sector": "Chemicals"},
    {"symbol": "INDIGOPNTS", "name": "Indigo Paints", "sector": "Chemicals"},
    {"symbol": "ASTRAL", "name": "Astral", "sector": "Consumer"},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries", "sector": "Consumer"},
    # Realty / Infra
    {"symbol": "GODREJPROP", "name": "Godrej Properties", "sector": "Realty"},
    {"symbol": "BRIGADE", "name": "Brigade Enterprises", "sector": "Realty"},
    {"symbol": "MAHLIFE", "name": "Mahindra Lifespace", "sector": "Realty"},
    {"symbol": "SUNTECK", "name": "Sunteck Realty", "sector": "Realty"},
    {"symbol": "SOBHA", "name": "Sobha", "sector": "Realty"},
    {"symbol": "KOLTEPATIL", "name": "Kolte Patil", "sector": "Realty"},
    {"symbol": "DLFLTD", "name": "DLF", "sector": "Realty"},
    {"symbol": "LODHA", "name": "Macrotech Developers", "sector": "Realty"},
    {"symbol": "ANANTRAJ", "name": "Anant Raj", "sector": "Realty"},
    {"symbol": "NCC", "name": "NCC", "sector": "Infrastructure"},
    {"symbol": "PNCINFRA", "name": "PNC Infratech", "sector": "Infrastructure"},
    {"symbol": "JKIL", "name": "J Kumar Infraprojects", "sector": "Infrastructure"},
    {"symbol": "HGINFRA", "name": "HG Infra Engineering", "sector": "Infrastructure"},
    {"symbol": "KEC", "name": "KEC International", "sector": "Capital Goods"},
    {"symbol": "KALPATPOWR", "name": "Kalpataru Projects", "sector": "Capital Goods"},
    {"symbol": "ENGINERSIN", "name": "Engineers India", "sector": "Capital Goods"},
    {"symbol": "ITDCEM", "name": "ITD Cementation", "sector": "Infrastructure"},
    {"symbol": "GPIL", "name": "Godawari Power & Ispat", "sector": "Metals"},
    {"symbol": "SRF", "name": "SRF", "sector": "Chemicals"},
    {"symbol": "JBMA", "name": "JBM Auto", "sector": "Auto"},
    {"symbol": "ORIENTREF", "name": "Orient Refractories", "sector": "Metals"},
    {"symbol": "RHIM", "name": "RHI Magnesita India", "sector": "Metals"},
    # Energy / Power
    {"symbol": "MAHANAGAR", "name": "Mahanagar Gas", "sector": "Energy"},
    {"symbol": "GUJGASLTD", "name": "Gujarat Gas", "sector": "Energy"},
    {"symbol": "IGL", "name": "Indraprastha Gas", "sector": "Energy"},
    {"symbol": "ATUL", "name": "Atul", "sector": "Chemicals"},
    {"symbol": "AEGISCHEM", "name": "Aegis Logistics", "sector": "Energy"},
    {"symbol": "CASTROLIND", "name": "Castrol India", "sector": "Energy"},
    {"symbol": "GSPL", "name": "Gujarat State Petronet", "sector": "Energy"},
    {"symbol": "JSWENERGY", "name": "JSW Energy", "sector": "Power"},
    {"symbol": "NHPC", "name": "NHPC", "sector": "Power"},
    {"symbol": "SJVN", "name": "SJVN", "sector": "Power"},
    {"symbol": "RPOWER", "name": "Reliance Power", "sector": "Power"},
    {"symbol": "INOXWIND", "name": "Inox Wind", "sector": "Power"},
    {"symbol": "ORIENTGREEN", "name": "Orient Green Power", "sector": "Power"},
    # Textiles / Misc
    {"symbol": "TRIDENT", "name": "Trident", "sector": "Textiles"},
    {"symbol": "WELSPUNLIV", "name": "Welspun Living", "sector": "Textiles"},
    {"symbol": "ARVIND", "name": "Arvind", "sector": "Textiles"},
    {"symbol": "RAYMOND", "name": "Raymond", "sector": "Textiles"},
    {"symbol": "VARDHMNTEX", "name": "Vardhman Textiles", "sector": "Textiles"},
    {"symbol": "PAGEIND", "name": "Page Industries", "sector": "Textiles"},
    {"symbol": "LUXIND", "name": "Lux Industries", "sector": "Textiles"},
    {"symbol": "SIYSIL", "name": "SIYSIL Mills", "sector": "Textiles"},
    {"symbol": "GOKEX", "name": "Gokaldas Exports", "sector": "Textiles"},
    {"symbol": "RELAXO", "name": "Relaxo Footwears", "sector": "Consumer"},
    {"symbol": "BATAINDIA", "name": "Bata India", "sector": "Consumer"},
    {"symbol": "METROBRAND", "name": "Metro Brands", "sector": "Retail"},
    {"symbol": "VEDL", "name": "Vedanta", "sector": "Metals"},
    {"symbol": "POLYPLEX", "name": "Polyplex Corporation", "sector": "Chemicals"},
    {"symbol": "GUJTHEM", "name": "Gujarat Themis Biosyn", "sector": "Pharma"},
    # Specialty / New-age
    {"symbol": "INDIAMART", "name": "IndiaMART", "sector": "Internet"},
    {"symbol": "JUSTDIAL", "name": "Just Dial", "sector": "Internet"},
    {"symbol": "EASEMYTRIP", "name": "Easy Trip Planners", "sector": "Travel"},
    {"symbol": "IXIGO", "name": "Le Travenues Tech (ixigo)", "sector": "Travel"},
    {"symbol": "RAILTEL", "name": "RailTel", "sector": "Telecom"},
    {"symbol": "TEJASNET", "name": "Tejas Networks", "sector": "Telecom"},
    {"symbol": "STLTECH", "name": "Sterlite Technologies", "sector": "Telecom"},
    {"symbol": "HFCL", "name": "HFCL", "sector": "Telecom"},
    {"symbol": "ITI", "name": "ITI Limited", "sector": "Telecom"},
    {"symbol": "DEN", "name": "DEN Networks", "sector": "Media"},
    {"symbol": "TV18BRDCST", "name": "TV18 Broadcast", "sector": "Media"},
    {"symbol": "NETWORK18", "name": "Network18 Media", "sector": "Media"},
    {"symbol": "DBCORP", "name": "DB Corp", "sector": "Media"},
    {"symbol": "JAGRAN", "name": "Jagran Prakashan", "sector": "Media"},
    {"symbol": "HATSUN", "name": "Hatsun Agro", "sector": "FMCG"},
    {"symbol": "DODLA", "name": "Dodla Dairy", "sector": "FMCG"},
    {"symbol": "HERITGFOOD", "name": "Heritage Foods", "sector": "FMCG"},
    {"symbol": "RAJESHEXPO", "name": "Rajesh Exports", "sector": "Consumer"},
    {"symbol": "KALYANKJIL", "name": "Kalyan Jewellers", "sector": "Retail"},
    {"symbol": "PCJEWELLER", "name": "PC Jeweller", "sector": "Retail"},
    {"symbol": "VAIBHAVGBL", "name": "Vaibhav Global", "sector": "Retail"},
    {"symbol": "VMART", "name": "V-Mart Retail", "sector": "Retail"},
    {"symbol": "SHOPERSTOP", "name": "Shoppers Stop", "sector": "Retail"},
    {"symbol": "SPENCERS", "name": "Spencer's Retail", "sector": "Retail"},
    {"symbol": "PVRINOX", "name": "PVR Inox", "sector": "Media"},
    {"symbol": "INOXLEISUR", "name": "Inox Leisure", "sector": "Media"},
    # Defence
    {"symbol": "BDL", "name": "Bharat Dynamics", "sector": "Defence"},
    {"symbol": "GRSE", "name": "Garden Reach Shipbuilders", "sector": "Defence"},
    {"symbol": "DATAPATTNS", "name": "Data Patterns", "sector": "Defence"},
    {"symbol": "MIDHANI", "name": "Mishra Dhatu Nigam", "sector": "Defence"},
    {"symbol": "HBLPOWER", "name": "HBL Power Systems", "sector": "Defence"},
    # Logistics
    {"symbol": "BLUEDART", "name": "Blue Dart Express", "sector": "Logistics"},
    {"symbol": "TCI", "name": "Transport Corp of India", "sector": "Logistics"},
    {"symbol": "VRLLOG", "name": "VRL Logistics", "sector": "Logistics"},
    {"symbol": "GATI", "name": "Gati", "sector": "Logistics"},
    {"symbol": "MAHLOG", "name": "Mahindra Logistics", "sector": "Logistics"},
    {"symbol": "DELHIVERY", "name": "Delhivery", "sector": "Logistics"},
    {"symbol": "SNOWMAN", "name": "Snowman Logistics", "sector": "Logistics"},
    {"symbol": "ALLCARGO", "name": "Allcargo Logistics", "sector": "Logistics"},
    {"symbol": "JWL", "name": "Jupiter Wagons", "sector": "Capital Goods"},
    {"symbol": "TITAGARH", "name": "Titagarh Rail Systems", "sector": "Capital Goods"},
    {"symbol": "TEXRAIL", "name": "Texmaco Rail", "sector": "Capital Goods"},
    {"symbol": "ELECON", "name": "Elecon Engineering", "sector": "Capital Goods"},
    # Misc Indian large/mid caps
    {"symbol": "VOLTAMP", "name": "Voltamp Transformers", "sector": "Capital Goods"},
    {"symbol": "CGCL", "name": "Capri Global", "sector": "Financial"},
    {"symbol": "CESC", "name": "CESC", "sector": "Power"},
    {"symbol": "CENTURYTEX", "name": "Century Textiles", "sector": "Cement"},
    {"symbol": "JKPAPER", "name": "JK Paper", "sector": "Materials"},
    {"symbol": "WSTCSTPAPR", "name": "West Coast Paper", "sector": "Materials"},
    {"symbol": "RAINBOWHSP", "name": "Rainbow Children's Medicare", "sector": "Healthcare"},
    {"symbol": "DEEPAKFERT", "name": "Deepak Fertilizers", "sector": "Chemicals"},
    {"symbol": "COROMANDEL", "name": "Coromandel International", "sector": "Chemicals"},
    {"symbol": "RALLIS", "name": "Rallis India", "sector": "Chemicals"},
    {"symbol": "BAYERCROP", "name": "Bayer CropScience", "sector": "Chemicals"},
    {"symbol": "SUMICHEM", "name": "Sumitomo Chemical", "sector": "Chemicals"},
    {"symbol": "DHANUKA", "name": "Dhanuka Agritech", "sector": "Chemicals"},
    {"symbol": "BASF", "name": "BASF India", "sector": "Chemicals"},
    {"symbol": "PIDILITIND", "name": "Pidilite Industries", "sector": "Chemicals"},
    {"symbol": "TATAINVEST", "name": "Tata Investment Corp", "sector": "Financial"},
    {"symbol": "NUVAMA", "name": "Nuvama Wealth", "sector": "Financial"},
    {"symbol": "ANANTRAJ", "name": "Anant Raj", "sector": "Realty"},
    {"symbol": "CARTRADE", "name": "Cartrade Tech", "sector": "Internet"},
    {"symbol": "PVR", "name": "PVR Inox", "sector": "Media"},
    {"symbol": "ADANITRANS", "name": "Adani Energy Solutions", "sector": "Power"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power", "sector": "Power"},
    {"symbol": "EQUINOX", "name": "Equinox India Developments", "sector": "Realty"},
    {"symbol": "AURIONPRO", "name": "Aurionpro Solutions", "sector": "IT"},
    {"symbol": "KFINTECH", "name": "KFin Technologies", "sector": "Financial"},
    {"symbol": "CAMS", "name": "Computer Age Mgmt Services", "sector": "Financial"},
    {"symbol": "BSOFT", "name": "Birlasoft", "sector": "IT"},
    {"symbol": "RTNPOWER", "name": "RattanIndia Power", "sector": "Power"},
    {"symbol": "RTNINDIA", "name": "RattanIndia Enterprises", "sector": "Diversified"},
    {"symbol": "HONASA", "name": "Honasa Consumer (Mamaearth)", "sector": "FMCG"},
    {"symbol": "JIOFIN", "name": "Jio Financial", "sector": "Financial"},
    {"symbol": "KPIL", "name": "Kalpataru Projects", "sector": "Infrastructure"},
    {"symbol": "POWERINDIA", "name": "Hitachi Energy India", "sector": "Capital Goods"},
    {"symbol": "GESHIP", "name": "Great Eastern Shipping", "sector": "Logistics"},
    {"symbol": "SCI", "name": "Shipping Corp of India", "sector": "Logistics"},
    {"symbol": "HUDCO", "name": "HUDCO", "sector": "Financial"},
    {"symbol": "IRCON", "name": "IRCON International", "sector": "Infrastructure"},
    {"symbol": "RITES", "name": "RITES", "sector": "Infrastructure"},
    {"symbol": "RVNL", "name": "Rail Vikas Nigam", "sector": "Infrastructure"},
    {"symbol": "ELECTCAST", "name": "Electrosteel Castings", "sector": "Metals"},
    {"symbol": "JSWHL", "name": "JSW Holdings", "sector": "Diversified"},
    {"symbol": "DOMS", "name": "DOMS Industries", "sector": "Consumer"},
    {"symbol": "CELLO", "name": "Cello World", "sector": "Consumer"},
]
