"""NSE universe definitions: Nifty 50 / Nifty 100 / Nifty 200 / Nifty 500."""
from nifty50 import NIFTY_50
from nifty500_extra import NIFTY_500_EXTRA

# Nifty Next 50 (the 50 large-caps just outside Nifty 50). Together with Nifty 50 = Nifty 100.
NIFTY_NEXT_50 = [
    {"symbol": "ABB", "name": "ABB India", "sector": "Capital Goods"},
    {"symbol": "ACC", "name": "ACC", "sector": "Cement"},
    {"symbol": "ADANIGREEN", "name": "Adani Green Energy", "sector": "Power"},
    {"symbol": "ADANIPOWER", "name": "Adani Power", "sector": "Power"},
    {"symbol": "ATGL", "name": "Adani Total Gas", "sector": "Energy"},
    {"symbol": "AMBUJACEM", "name": "Ambuja Cements", "sector": "Cement"},
    {"symbol": "BAJAJHLDNG", "name": "Bajaj Holdings", "sector": "Financial"},
    {"symbol": "BANKBARODA", "name": "Bank of Baroda", "sector": "Financial"},
    {"symbol": "BERGEPAINT", "name": "Berger Paints", "sector": "Consumer"},
    {"symbol": "BOSCHLTD", "name": "Bosch", "sector": "Auto"},
    {"symbol": "CANBK", "name": "Canara Bank", "sector": "Financial"},
    {"symbol": "CHOLAFIN", "name": "Cholamandalam Investment", "sector": "Financial"},
    {"symbol": "COLPAL", "name": "Colgate Palmolive", "sector": "FMCG"},
    {"symbol": "DABUR", "name": "Dabur India", "sector": "FMCG"},
    {"symbol": "DLF", "name": "DLF", "sector": "Realty"},
    {"symbol": "DMART", "name": "Avenue Supermarts", "sector": "Retail"},
    {"symbol": "GAIL", "name": "GAIL India", "sector": "Energy"},
    {"symbol": "GODREJCP", "name": "Godrej Consumer", "sector": "FMCG"},
    {"symbol": "HAL", "name": "Hindustan Aeronautics", "sector": "Defence"},
    {"symbol": "HAVELLS", "name": "Havells India", "sector": "Consumer"},
    {"symbol": "HDFCAMC", "name": "HDFC AMC", "sector": "Financial"},
    {"symbol": "ICICIGI", "name": "ICICI Lombard", "sector": "Insurance"},
    {"symbol": "ICICIPRULI", "name": "ICICI Prudential Life", "sector": "Insurance"},
    {"symbol": "IOC", "name": "Indian Oil Corp", "sector": "Energy"},
    {"symbol": "IRCTC", "name": "IRCTC", "sector": "Travel"},
    {"symbol": "IRFC", "name": "Indian Railway Finance", "sector": "Financial"},
    {"symbol": "JINDALSTEL", "name": "Jindal Steel", "sector": "Metals"},
    {"symbol": "LICI", "name": "Life Insurance Corp", "sector": "Insurance"},
    {"symbol": "LTIM", "name": "LTIMindtree", "sector": "IT"},
    {"symbol": "MARICO", "name": "Marico", "sector": "FMCG"},
    {"symbol": "MOTHERSON", "name": "Motherson Sumi", "sector": "Auto"},
    {"symbol": "NAUKRI", "name": "Info Edge", "sector": "Internet"},
    {"symbol": "PIDILITIND", "name": "Pidilite Industries", "sector": "Chemicals"},
    {"symbol": "PFC", "name": "Power Finance Corp", "sector": "Financial"},
    {"symbol": "PNB", "name": "Punjab National Bank", "sector": "Financial"},
    {"symbol": "RECLTD", "name": "REC Limited", "sector": "Financial"},
    {"symbol": "SHREECEM", "name": "Shree Cement", "sector": "Cement"},
    {"symbol": "SIEMENS", "name": "Siemens", "sector": "Capital Goods"},
    {"symbol": "SRF", "name": "SRF", "sector": "Chemicals"},
    {"symbol": "TATAPOWER", "name": "Tata Power", "sector": "Power"},
    {"symbol": "TORNTPHARM", "name": "Torrent Pharma", "sector": "Pharma"},
    {"symbol": "TVSMOTOR", "name": "TVS Motor", "sector": "Auto"},
    {"symbol": "UNITDSPR", "name": "United Spirits", "sector": "FMCG"},
    {"symbol": "VBL", "name": "Varun Beverages", "sector": "FMCG"},
    {"symbol": "VEDL", "name": "Vedanta", "sector": "Metals"},
    {"symbol": "ZOMATO", "name": "Zomato", "sector": "Internet"},
    {"symbol": "ZYDUSLIFE", "name": "Zydus Lifesciences", "sector": "Pharma"},
    {"symbol": "INDUSTOWER", "name": "Indus Towers", "sector": "Telecom"},
    {"symbol": "JIOFIN", "name": "Jio Financial", "sector": "Financial"},
    {"symbol": "BANKINDIA", "name": "Bank of India", "sector": "Financial"},
]

# Nifty Midcap 100 — the next tier, together with Nifty 100 = Nifty 200.
NIFTY_MIDCAP_100 = [
    {"symbol": "AUROPHARMA", "name": "Aurobindo Pharma", "sector": "Pharma"},
    {"symbol": "ABCAPITAL", "name": "Aditya Birla Capital", "sector": "Financial"},
    {"symbol": "ABFRL", "name": "Aditya Birla Fashion", "sector": "Retail"},
    {"symbol": "ALKEM", "name": "Alkem Laboratories", "sector": "Pharma"},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland", "sector": "Auto"},
    {"symbol": "ASTRAL", "name": "Astral", "sector": "Consumer"},
    {"symbol": "AUBANK", "name": "AU Small Finance Bank", "sector": "Financial"},
    {"symbol": "BALKRISIND", "name": "Balkrishna Industries", "sector": "Auto"},
    {"symbol": "BANDHANBNK", "name": "Bandhan Bank", "sector": "Financial"},
    {"symbol": "BHARATFORG", "name": "Bharat Forge", "sector": "Capital Goods"},
    {"symbol": "BEL", "name": "Bharat Electronics", "sector": "Defence"},
    {"symbol": "BHEL", "name": "BHEL", "sector": "Capital Goods"},
    {"symbol": "BIOCON", "name": "Biocon", "sector": "Pharma"},
    {"symbol": "CGPOWER", "name": "CG Power", "sector": "Capital Goods"},
    {"symbol": "COFORGE", "name": "Coforge", "sector": "IT"},
    {"symbol": "CONCOR", "name": "Container Corp", "sector": "Logistics"},
    {"symbol": "CUMMINSIND", "name": "Cummins India", "sector": "Capital Goods"},
    {"symbol": "DEEPAKNTR", "name": "Deepak Nitrite", "sector": "Chemicals"},
    {"symbol": "DIXON", "name": "Dixon Technologies", "sector": "Consumer"},
    {"symbol": "ESCORTS", "name": "Escorts Kubota", "sector": "Auto"},
    {"symbol": "EXIDEIND", "name": "Exide Industries", "sector": "Auto"},
    {"symbol": "FEDERALBNK", "name": "Federal Bank", "sector": "Financial"},
    {"symbol": "GLAND", "name": "Gland Pharma", "sector": "Pharma"},
    {"symbol": "GMRINFRA", "name": "GMR Airports", "sector": "Infrastructure"},
    {"symbol": "GODREJPROP", "name": "Godrej Properties", "sector": "Realty"},
    {"symbol": "HDFCAMC", "name": "HDFC AMC", "sector": "Financial"},
    {"symbol": "HINDPETRO", "name": "HPCL", "sector": "Energy"},
    {"symbol": "IDFCFIRSTB", "name": "IDFC First Bank", "sector": "Financial"},
    {"symbol": "INDHOTEL", "name": "Indian Hotels", "sector": "Hotels"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank", "sector": "Financial"},
    {"symbol": "IPCALAB", "name": "IPCA Laboratories", "sector": "Pharma"},
    {"symbol": "JSL", "name": "Jindal Stainless", "sector": "Metals"},
    {"symbol": "JUBLFOOD", "name": "Jubilant FoodWorks", "sector": "Consumer"},
    {"symbol": "KPITTECH", "name": "KPIT Technologies", "sector": "IT"},
    {"symbol": "LICHSGFIN", "name": "LIC Housing Finance", "sector": "Financial"},
    {"symbol": "LUPIN", "name": "Lupin", "sector": "Pharma"},
    {"symbol": "MFSL", "name": "Max Financial", "sector": "Insurance"},
    {"symbol": "MPHASIS", "name": "Mphasis", "sector": "IT"},
    {"symbol": "MRF", "name": "MRF", "sector": "Auto"},
    {"symbol": "MUTHOOTFIN", "name": "Muthoot Finance", "sector": "Financial"},
    {"symbol": "NMDC", "name": "NMDC", "sector": "Metals"},
    {"symbol": "OBEROIRLTY", "name": "Oberoi Realty", "sector": "Realty"},
    {"symbol": "OFSS", "name": "Oracle Financial", "sector": "IT"},
    {"symbol": "PAGEIND", "name": "Page Industries", "sector": "Retail"},
    {"symbol": "PERSISTENT", "name": "Persistent Systems", "sector": "IT"},
    {"symbol": "PETRONET", "name": "Petronet LNG", "sector": "Energy"},
    {"symbol": "PIIND", "name": "PI Industries", "sector": "Chemicals"},
    {"symbol": "POLYCAB", "name": "Polycab India", "sector": "Capital Goods"},
    {"symbol": "POONAWALLA", "name": "Poonawalla Fincorp", "sector": "Financial"},
    {"symbol": "PRESTIGE", "name": "Prestige Estates", "sector": "Realty"},
    {"symbol": "RVNL", "name": "Rail Vikas Nigam", "sector": "Infrastructure"},
    {"symbol": "SAIL", "name": "SAIL", "sector": "Metals"},
    {"symbol": "SOLARINDS", "name": "Solar Industries", "sector": "Defence"},
    {"symbol": "SONACOMS", "name": "Sona BLW Precision", "sector": "Auto"},
    {"symbol": "SUNDARMFIN", "name": "Sundaram Finance", "sector": "Financial"},
    {"symbol": "SUPREMEIND", "name": "Supreme Industries", "sector": "Consumer"},
    {"symbol": "SUZLON", "name": "Suzlon Energy", "sector": "Power"},
    {"symbol": "TATACOMM", "name": "Tata Communications", "sector": "Telecom"},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi", "sector": "IT"},
    {"symbol": "TIINDIA", "name": "Tube Investments", "sector": "Capital Goods"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power", "sector": "Power"},
    {"symbol": "UBL", "name": "United Breweries", "sector": "FMCG"},
    {"symbol": "UPL", "name": "UPL", "sector": "Chemicals"},
    {"symbol": "VOLTAS", "name": "Voltas", "sector": "Consumer"},
    {"symbol": "YESBANK", "name": "Yes Bank", "sector": "Financial"},
    {"symbol": "ZEEL", "name": "Zee Entertainment", "sector": "Media"},
    {"symbol": "POLICYBZR", "name": "PB Fintech", "sector": "Financial"},
    {"symbol": "PAYTM", "name": "One 97 Communications", "sector": "Financial"},
    {"symbol": "NYKAA", "name": "FSN E-Commerce", "sector": "Retail"},
    {"symbol": "MAZDOCK", "name": "Mazagon Dock", "sector": "Defence"},
    {"symbol": "CRISIL", "name": "Crisil", "sector": "Financial"},
    {"symbol": "GUJGASLTD", "name": "Gujarat Gas", "sector": "Energy"},
    {"symbol": "AARTIIND", "name": "Aarti Industries", "sector": "Chemicals"},
    {"symbol": "ABBOTINDIA", "name": "Abbott India", "sector": "Pharma"},
    {"symbol": "APLAPOLLO", "name": "APL Apollo Tubes", "sector": "Metals"},
    {"symbol": "ASTRAZEN", "name": "AstraZeneca Pharma", "sector": "Pharma"},
    {"symbol": "BAJAJELEC", "name": "Bajaj Electricals", "sector": "Consumer"},
    {"symbol": "BSE", "name": "BSE Ltd", "sector": "Financial"},
    {"symbol": "CARBORUNIV", "name": "Carborundum Universal", "sector": "Capital Goods"},
    {"symbol": "CDSL", "name": "Central Depository", "sector": "Financial"},
    {"symbol": "CESC", "name": "CESC", "sector": "Power"},
    {"symbol": "CHAMBLFERT", "name": "Chambal Fertilisers", "sector": "Chemicals"},
    {"symbol": "CROMPTON", "name": "Crompton Greaves", "sector": "Consumer"},
    {"symbol": "CYIENT", "name": "Cyient", "sector": "IT"},
    {"symbol": "EIDPARRY", "name": "EID Parry", "sector": "FMCG"},
    {"symbol": "FACT", "name": "Fertilisers & Chemicals Travancore", "sector": "Chemicals"},
    {"symbol": "FINCABLES", "name": "Finolex Cables", "sector": "Capital Goods"},
    {"symbol": "GLENMARK", "name": "Glenmark Pharma", "sector": "Pharma"},
    {"symbol": "GRAPHITE", "name": "Graphite India", "sector": "Capital Goods"},
    {"symbol": "GSPL", "name": "Gujarat State Petronet", "sector": "Energy"},
    {"symbol": "HINDCOPPER", "name": "Hindustan Copper", "sector": "Metals"},
    {"symbol": "HUDCO", "name": "HUDCO", "sector": "Financial"},
    {"symbol": "IDEA", "name": "Vodafone Idea", "sector": "Telecom"},
    {"symbol": "IEX", "name": "Indian Energy Exchange", "sector": "Power"},
    {"symbol": "IIFL", "name": "IIFL Finance", "sector": "Financial"},
    {"symbol": "IRB", "name": "IRB Infrastructure", "sector": "Infrastructure"},
    {"symbol": "JKCEMENT", "name": "JK Cement", "sector": "Cement"},
    {"symbol": "KAJARIACER", "name": "Kajaria Ceramics", "sector": "Consumer"},
    {"symbol": "LATENTVIEW", "name": "Latent View Analytics", "sector": "IT"},
    {"symbol": "LAURUSLABS", "name": "Laurus Labs", "sector": "Pharma"},
    {"symbol": "LINDEINDIA", "name": "Linde India", "sector": "Chemicals"},
    {"symbol": "M&MFIN", "name": "M&M Financial", "sector": "Financial"},
    {"symbol": "MANAPPURAM", "name": "Manappuram Finance", "sector": "Financial"},
    {"symbol": "MCX", "name": "MCX India", "sector": "Financial"},
    {"symbol": "NATIONALUM", "name": "National Aluminium", "sector": "Metals"},
    {"symbol": "OIL", "name": "Oil India", "sector": "Energy"},
    {"symbol": "PEL", "name": "Piramal Enterprises", "sector": "Financial"},
    {"symbol": "PHOENIXLTD", "name": "Phoenix Mills", "sector": "Realty"},
    {"symbol": "PRAJIND", "name": "Praj Industries", "sector": "Capital Goods"},
    {"symbol": "RAMCOCEM", "name": "Ramco Cements", "sector": "Cement"},
    {"symbol": "RBLBANK", "name": "RBL Bank", "sector": "Financial"},
    {"symbol": "SBICARD", "name": "SBI Cards", "sector": "Financial"},
    {"symbol": "STARHEALTH", "name": "Star Health Insurance", "sector": "Insurance"},
    {"symbol": "SUNTV", "name": "Sun TV Network", "sector": "Media"},
    {"symbol": "SYNGENE", "name": "Syngene International", "sector": "Pharma"},
    {"symbol": "THERMAX", "name": "Thermax", "sector": "Capital Goods"},
    {"symbol": "TRIDENT", "name": "Trident", "sector": "Textiles"},
    {"symbol": "UJJIVANSFB", "name": "Ujjivan SFB", "sector": "Financial"},
]

# Dedupe (in case any overlap)
def _dedupe(lst):
    seen = set()
    out = []
    for s in lst:
        if s["symbol"] not in seen:
            seen.add(s["symbol"])
            out.append(s)
    return out


NIFTY_100 = _dedupe(NIFTY_50 + NIFTY_NEXT_50)
NIFTY_200 = _dedupe(NIFTY_100 + NIFTY_MIDCAP_100)
NIFTY_500 = _dedupe(NIFTY_200 + NIFTY_500_EXTRA)


UNIVERSES = {
    "nifty50": ("Nifty 50", NIFTY_50),
    "nifty100": ("Nifty 100", NIFTY_100),
    "nifty200": ("Nifty 200", NIFTY_200),
    "nifty500": ("Nifty 500", NIFTY_500),
}


def get_universe(name: str):
    name = (name or "nifty50").lower()
    if name not in UNIVERSES:
        return UNIVERSES["nifty50"][1]
    return UNIVERSES[name][1]
